/*
 * This file is generated by jOOQ.
 */
package com.sample.`public`.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), com.sample.`public`.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, arrayOf(com.sample.`public`.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
