# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'