/*
 * This file is generated by jOOQ.
 */
package com.sample.information_schema.tables


import com.sample.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class _PgForeignDataWrappers(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("create view \"_pg_foreign_data_wrappers\" as  SELECT w.oid,\n    w.fdwowner,\n    w.fdwoptions,\n    (current_database())::information_schema.sql_identifier AS foreign_data_wrapper_catalog,\n    (w.fdwname)::information_schema.sql_identifier AS foreign_data_wrapper_name,\n    (u.rolname)::information_schema.sql_identifier AS authorization_identifier,\n    ('c'::character varying)::information_schema.character_data AS foreign_data_wrapper_language\n   FROM pg_foreign_data_wrapper w,\n    pg_authid u\n  WHERE ((u.oid = w.fdwowner) AND (pg_has_role(w.fdwowner, 'USAGE'::text) OR has_foreign_data_wrapper_privilege(w.oid, 'USAGE'::text)));")
) {
    companion object {

        /**
         * The reference instance of
         * <code>information_schema._pg_foreign_data_wrappers</code>
         */
        val _PG_FOREIGN_DATA_WRAPPERS: _PgForeignDataWrappers = _PgForeignDataWrappers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.oid</code>.
     */
    val OID: TableField<Record, Long?> = createField(DSL.name("oid"), SQLDataType.BIGINT, this, "")

    /**
     * The column
     * <code>information_schema._pg_foreign_data_wrappers.fdwowner</code>.
     */
    val FDWOWNER: TableField<Record, Long?> = createField(DSL.name("fdwowner"), SQLDataType.BIGINT, this, "")

    /**
     * The column
     * <code>information_schema._pg_foreign_data_wrappers.fdwoptions</code>.
     */
    val FDWOPTIONS: TableField<Record, Array<String?>?> = createField(DSL.name("fdwoptions"), SQLDataType.CLOB.getArrayDataType(), this, "")

    /**
     * The column
     * <code>information_schema._pg_foreign_data_wrappers.foreign_data_wrapper_catalog</code>.
     */
    val FOREIGN_DATA_WRAPPER_CATALOG: TableField<Record, String?> = createField(DSL.name("foreign_data_wrapper_catalog"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column
     * <code>information_schema._pg_foreign_data_wrappers.foreign_data_wrapper_name</code>.
     */
    val FOREIGN_DATA_WRAPPER_NAME: TableField<Record, String?> = createField(DSL.name("foreign_data_wrapper_name"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column
     * <code>information_schema._pg_foreign_data_wrappers.authorization_identifier</code>.
     */
    val AUTHORIZATION_IDENTIFIER: TableField<Record, String?> = createField(DSL.name("authorization_identifier"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column
     * <code>information_schema._pg_foreign_data_wrappers.foreign_data_wrapper_language</code>.
     */
    val FOREIGN_DATA_WRAPPER_LANGUAGE: TableField<Record, String?> = createField(DSL.name("foreign_data_wrapper_language"), com.sample.information_schema.domains.CHARACTER_DATA.getDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased
     * <code>information_schema._pg_foreign_data_wrappers</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>information_schema._pg_foreign_data_wrappers</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema._pg_foreign_data_wrappers</code> table
     * reference
     */
    constructor(): this(DSL.name("_pg_foreign_data_wrappers"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, _PG_FOREIGN_DATA_WRAPPERS, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): _PgForeignDataWrappers = _PgForeignDataWrappers(DSL.name(alias), this)
    override fun `as`(alias: Name): _PgForeignDataWrappers = _PgForeignDataWrappers(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): _PgForeignDataWrappers = _PgForeignDataWrappers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): _PgForeignDataWrappers = _PgForeignDataWrappers(name, null)
}
