/*
 * This file is generated by jOOQ.
 */
package com.sample.information_schema.tables


import com.sample.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class _PgUserMappings(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("create view \"_pg_user_mappings\" as  SELECT um.oid,\n    um.umoptions,\n    um.umuser,\n    (COALESCE(u.rolname, 'PUBLIC'::name))::information_schema.sql_identifier AS authorization_identifier,\n    s.foreign_server_catalog,\n    s.foreign_server_name,\n    s.authorization_identifier AS srvowner\n   FROM (pg_user_mapping um\n     LEFT JOIN pg_authid u ON ((u.oid = um.umuser))),\n    information_schema._pg_foreign_servers s\n  WHERE (s.oid = um.umserver);")
) {
    companion object {

        /**
         * The reference instance of
         * <code>information_schema._pg_user_mappings</code>
         */
        val _PG_USER_MAPPINGS: _PgUserMappings = _PgUserMappings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema._pg_user_mappings.oid</code>.
     */
    val OID: TableField<Record, Long?> = createField(DSL.name("oid"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>information_schema._pg_user_mappings.umoptions</code>.
     */
    val UMOPTIONS: TableField<Record, Array<String?>?> = createField(DSL.name("umoptions"), SQLDataType.CLOB.getArrayDataType(), this, "")

    /**
     * The column <code>information_schema._pg_user_mappings.umuser</code>.
     */
    val UMUSER: TableField<Record, Long?> = createField(DSL.name("umuser"), SQLDataType.BIGINT, this, "")

    /**
     * The column
     * <code>information_schema._pg_user_mappings.authorization_identifier</code>.
     */
    val AUTHORIZATION_IDENTIFIER: TableField<Record, String?> = createField(DSL.name("authorization_identifier"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column
     * <code>information_schema._pg_user_mappings.foreign_server_catalog</code>.
     */
    val FOREIGN_SERVER_CATALOG: TableField<Record, String?> = createField(DSL.name("foreign_server_catalog"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column
     * <code>information_schema._pg_user_mappings.foreign_server_name</code>.
     */
    val FOREIGN_SERVER_NAME: TableField<Record, String?> = createField(DSL.name("foreign_server_name"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column <code>information_schema._pg_user_mappings.srvowner</code>.
     */
    val SRVOWNER: TableField<Record, String?> = createField(DSL.name("srvowner"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema._pg_user_mappings</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema._pg_user_mappings</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema._pg_user_mappings</code> table
     * reference
     */
    constructor(): this(DSL.name("_pg_user_mappings"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, _PG_USER_MAPPINGS, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): _PgUserMappings = _PgUserMappings(DSL.name(alias), this)
    override fun `as`(alias: Name): _PgUserMappings = _PgUserMappings(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): _PgUserMappings = _PgUserMappings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): _PgUserMappings = _PgUserMappings(name, null)
}
