/*
 * This file is generated by jOOQ.
 */
package com.sample.information_schema.tables


import com.sample.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SqlSizing(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>information_schema.sql_sizing</code>
         */
        val SQL_SIZING: SqlSizing = SqlSizing()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema.sql_sizing.sizing_id</code>.
     */
    val SIZING_ID: TableField<Record, Int?> = createField(DSL.name("sizing_id"), com.sample.information_schema.domains.CARDINAL_NUMBER.getDataType(), this, "")

    /**
     * The column <code>information_schema.sql_sizing.sizing_name</code>.
     */
    val SIZING_NAME: TableField<Record, String?> = createField(DSL.name("sizing_name"), com.sample.information_schema.domains.CHARACTER_DATA.getDataType(), this, "")

    /**
     * The column <code>information_schema.sql_sizing.supported_value</code>.
     */
    val SUPPORTED_VALUE: TableField<Record, Int?> = createField(DSL.name("supported_value"), com.sample.information_schema.domains.CARDINAL_NUMBER.getDataType(), this, "")

    /**
     * The column <code>information_schema.sql_sizing.comments</code>.
     */
    val COMMENTS: TableField<Record, String?> = createField(DSL.name("comments"), com.sample.information_schema.domains.CHARACTER_DATA.getDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema.sql_sizing</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema.sql_sizing</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema.sql_sizing</code> table reference
     */
    constructor(): this(DSL.name("sql_sizing"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, SQL_SIZING, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): SqlSizing = SqlSizing(DSL.name(alias), this)
    override fun `as`(alias: Name): SqlSizing = SqlSizing(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SqlSizing = SqlSizing(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SqlSizing = SqlSizing(name, null)
}
