/*
 * This file is generated by jOOQ.
 */
package com.sample.information_schema.tables


import com.sample.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ViewTableUsage(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("create view \"view_table_usage\" as  SELECT DISTINCT (current_database())::information_schema.sql_identifier AS view_catalog,\n    (nv.nspname)::information_schema.sql_identifier AS view_schema,\n    (v.relname)::information_schema.sql_identifier AS view_name,\n    (current_database())::information_schema.sql_identifier AS table_catalog,\n    (nt.nspname)::information_schema.sql_identifier AS table_schema,\n    (t.relname)::information_schema.sql_identifier AS table_name\n   FROM pg_namespace nv,\n    pg_class v,\n    pg_depend dv,\n    pg_depend dt,\n    pg_class t,\n    pg_namespace nt\n  WHERE ((nv.oid = v.relnamespace) AND (v.relkind = 'v'::\"char\") AND (v.oid = dv.refobjid) AND (dv.refclassid = ('pg_class'::regclass)::oid) AND (dv.classid = ('pg_rewrite'::regclass)::oid) AND (dv.deptype = 'i'::\"char\") AND (dv.objid = dt.objid) AND (dv.refobjid <> dt.refobjid) AND (dt.classid = ('pg_rewrite'::regclass)::oid) AND (dt.refclassid = ('pg_class'::regclass)::oid) AND (dt.refobjid = t.oid) AND (t.relnamespace = nt.oid) AND (t.relkind = ANY (ARRAY['r'::\"char\", 'v'::\"char\", 'f'::\"char\", 'p'::\"char\"])) AND pg_has_role(t.relowner, 'USAGE'::text));")
) {
    companion object {

        /**
         * The reference instance of
         * <code>information_schema.view_table_usage</code>
         */
        val VIEW_TABLE_USAGE: ViewTableUsage = ViewTableUsage()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema.view_table_usage.view_catalog</code>.
     */
    val VIEW_CATALOG: TableField<Record, String?> = createField(DSL.name("view_catalog"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column <code>information_schema.view_table_usage.view_schema</code>.
     */
    val VIEW_SCHEMA: TableField<Record, String?> = createField(DSL.name("view_schema"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column <code>information_schema.view_table_usage.view_name</code>.
     */
    val VIEW_NAME: TableField<Record, String?> = createField(DSL.name("view_name"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column
     * <code>information_schema.view_table_usage.table_catalog</code>.
     */
    val TABLE_CATALOG: TableField<Record, String?> = createField(DSL.name("table_catalog"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column <code>information_schema.view_table_usage.table_schema</code>.
     */
    val TABLE_SCHEMA: TableField<Record, String?> = createField(DSL.name("table_schema"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    /**
     * The column <code>information_schema.view_table_usage.table_name</code>.
     */
    val TABLE_NAME: TableField<Record, String?> = createField(DSL.name("table_name"), com.sample.information_schema.domains.SQL_IDENTIFIER.getDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema.view_table_usage</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema.view_table_usage</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema.view_table_usage</code> table reference
     */
    constructor(): this(DSL.name("view_table_usage"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, VIEW_TABLE_USAGE, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): ViewTableUsage = ViewTableUsage(DSL.name(alias), this)
    override fun `as`(alias: Name): ViewTableUsage = ViewTableUsage(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ViewTableUsage = ViewTableUsage(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ViewTableUsage = ViewTableUsage(name, null)
}
