/*
 * This file is generated by jOOQ.
 */
package com.sample.pg_catalog.routines


import com.sample.pg_catalog.PgCatalog

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CurrentUser : AbstractRoutine<String>("current_user", PgCatalog.PG_CATALOG, SQLDataType.VARCHAR) {
    companion object {

        /**
         * The parameter <code>pg_catalog.current_user.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.VARCHAR, false, false)
    }

    init {
        returnParameter = RETURN_VALUE
    }
}
