/*
 * This file is generated by jOOQ.
 */
package com.sample.pg_catalog.routines


import com.sample.pg_catalog.PgCatalog

import java.time.OffsetDateTime

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgStatFile2 : AbstractRoutine<java.lang.Void>("pg_stat_file", PgCatalog.PG_CATALOG) {
    companion object {

        /**
         * The parameter <code>pg_catalog.pg_stat_file.filename</code>.
         */
        val FILENAME: Parameter<String?> = Internal.createParameter("filename", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.missing_ok</code>.
         */
        val MISSING_OK: Parameter<Boolean?> = Internal.createParameter("missing_ok", SQLDataType.BOOLEAN, false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.size</code>.
         */
        val SIZE: Parameter<Long?> = Internal.createParameter("size", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.access</code>.
         */
        val ACCESS: Parameter<OffsetDateTime?> = Internal.createParameter("access", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.modification</code>.
         */
        val MODIFICATION: Parameter<OffsetDateTime?> = Internal.createParameter("modification", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.change</code>.
         */
        val CHANGE: Parameter<OffsetDateTime?> = Internal.createParameter("change", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.creation</code>.
         */
        val CREATION: Parameter<OffsetDateTime?> = Internal.createParameter("creation", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false)

        /**
         * The parameter <code>pg_catalog.pg_stat_file.isdir</code>.
         */
        val ISDIR: Parameter<Boolean?> = Internal.createParameter("isdir", SQLDataType.BOOLEAN, false, false)
    }

    init {
        addInParameter(FILENAME)
        addInParameter(MISSING_OK)
        addOutParameter(SIZE)
        addOutParameter(ACCESS)
        addOutParameter(MODIFICATION)
        addOutParameter(CHANGE)
        addOutParameter(CREATION)
        addOutParameter(ISDIR)
        setOverloaded(true)
    }

    /**
     * Set the <code>filename</code> parameter IN value to the routine
     */
    fun setFilename(value: String?): Unit = setValue(FILENAME, value)

    /**
     * Set the <code>missing_ok</code> parameter IN value to the routine
     */
    fun setMissingOk(value: Boolean?): Unit = setValue(MISSING_OK, value)

    /**
     * Get the <code>size</code> parameter OUT value from the routine
     */
    fun getSize(): Long? = get(SIZE)

    /**
     * Get the <code>access</code> parameter OUT value from the routine
     */
    fun getAccess(): OffsetDateTime? = get(ACCESS)

    /**
     * Get the <code>modification</code> parameter OUT value from the routine
     */
    fun getModification(): OffsetDateTime? = get(MODIFICATION)

    /**
     * Get the <code>change</code> parameter OUT value from the routine
     */
    fun getChange(): OffsetDateTime? = get(CHANGE)

    /**
     * Get the <code>creation</code> parameter OUT value from the routine
     */
    fun getCreation(): OffsetDateTime? = get(CREATION)

    /**
     * Get the <code>isdir</code> parameter OUT value from the routine
     */
    fun getIsdir(): Boolean? = get(ISDIR)
}
