/*
 * This file is generated by jOOQ.
 */
package com.sample.pg_catalog.tables


import com.sample.pg_catalog.PgCatalog

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgAvailableExtensions(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("create view \"pg_available_extensions\" as  SELECT e.name,\n    e.default_version,\n    x.extversion AS installed_version,\n    e.comment\n   FROM (pg_available_extensions() e(name, default_version, comment)\n     LEFT JOIN pg_extension x ON ((e.name = x.extname)));")
) {
    companion object {

        /**
         * The reference instance of
         * <code>pg_catalog.pg_available_extensions</code>
         */
        val PG_AVAILABLE_EXTENSIONS: PgAvailableExtensions = PgAvailableExtensions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.pg_available_extensions.name</code>.
     */
    val NAME: TableField<Record, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>pg_catalog.pg_available_extensions.default_version</code>.
     */
    val DEFAULT_VERSION: TableField<Record, String?> = createField(DSL.name("default_version"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>pg_catalog.pg_available_extensions.installed_version</code>.
     */
    val INSTALLED_VERSION: TableField<Record, String?> = createField(DSL.name("installed_version"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>pg_catalog.pg_available_extensions.comment</code>.
     */
    val COMMENT: TableField<Record, String?> = createField(DSL.name("comment"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.pg_available_extensions</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.pg_available_extensions</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.pg_available_extensions</code> table reference
     */
    constructor(): this(DSL.name("pg_available_extensions"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, PG_AVAILABLE_EXTENSIONS, null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun `as`(alias: String): PgAvailableExtensions = PgAvailableExtensions(DSL.name(alias), this)
    override fun `as`(alias: Name): PgAvailableExtensions = PgAvailableExtensions(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PgAvailableExtensions = PgAvailableExtensions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PgAvailableExtensions = PgAvailableExtensions(name, null)
}
