/*
 * This file is generated by jOOQ.
 */
package com.sample.pg_catalog.tables


import com.sample.pg_catalog.PgCatalog

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgPublicationTables(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("create view \"pg_publication_tables\" as  SELECT p.pubname,\n    n.nspname AS schemaname,\n    c.relname AS tablename\n   FROM pg_publication p,\n    LATERAL pg_get_publication_tables((p.pubname)::text) gpt(relid),\n    (pg_class c\n     JOIN pg_namespace n ON ((n.oid = c.relnamespace)))\n  WHERE (c.oid = gpt.relid);")
) {
    companion object {

        /**
         * The reference instance of
         * <code>pg_catalog.pg_publication_tables</code>
         */
        val PG_PUBLICATION_TABLES: PgPublicationTables = PgPublicationTables()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.pg_publication_tables.pubname</code>.
     */
    val PUBNAME: TableField<Record, String?> = createField(DSL.name("pubname"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>pg_catalog.pg_publication_tables.schemaname</code>.
     */
    val SCHEMANAME: TableField<Record, String?> = createField(DSL.name("schemaname"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>pg_catalog.pg_publication_tables.tablename</code>.
     */
    val TABLENAME: TableField<Record, String?> = createField(DSL.name("tablename"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.pg_publication_tables</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.pg_publication_tables</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.pg_publication_tables</code> table reference
     */
    constructor(): this(DSL.name("pg_publication_tables"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, PG_PUBLICATION_TABLES, null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun `as`(alias: String): PgPublicationTables = PgPublicationTables(DSL.name(alias), this)
    override fun `as`(alias: Name): PgPublicationTables = PgPublicationTables(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PgPublicationTables = PgPublicationTables(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PgPublicationTables = PgPublicationTables(name, null)
}
