/*
 * This file is generated by jOOQ.
 */
package com.sample.pg_catalog.tables


import com.sample.pg_catalog.PgCatalog
import com.sample.pg_catalog.indexes.PG_TABLESPACE_OID_INDEX
import com.sample.pg_catalog.indexes.PG_TABLESPACE_SPCNAME_INDEX

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgTablespace(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>pg_catalog.pg_tablespace</code>
         */
        val PG_TABLESPACE: PgTablespace = PgTablespace()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.pg_tablespace.oid</code>.
     */
    val OID: TableField<Record, Long?> = createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>pg_catalog.pg_tablespace.spcname</code>.
     */
    val SPCNAME: TableField<Record, String?> = createField(DSL.name("spcname"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>pg_catalog.pg_tablespace.spcowner</code>.
     */
    val SPCOWNER: TableField<Record, Long?> = createField(DSL.name("spcowner"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>pg_catalog.pg_tablespace.spcacl</code>.
     */
    val SPCACL: TableField<Record, Array<String?>?> = createField(DSL.name("spcacl"), SQLDataType.VARCHAR.getArrayDataType(), this, "")

    /**
     * The column <code>pg_catalog.pg_tablespace.spcoptions</code>.
     */
    val SPCOPTIONS: TableField<Record, Array<String?>?> = createField(DSL.name("spcoptions"), SQLDataType.CLOB.getArrayDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.pg_tablespace</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.pg_tablespace</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.pg_tablespace</code> table reference
     */
    constructor(): this(DSL.name("pg_tablespace"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, PG_TABLESPACE, null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun getIndexes(): List<Index> = listOf(PG_TABLESPACE_OID_INDEX, PG_TABLESPACE_SPCNAME_INDEX)
    override fun `as`(alias: String): PgTablespace = PgTablespace(DSL.name(alias), this)
    override fun `as`(alias: Name): PgTablespace = PgTablespace(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PgTablespace = PgTablespace(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PgTablespace = PgTablespace(name, null)
}
