/*
 * This file is generated by jOOQ.
 */
package com.sample.pg_catalog.tables


import com.sample.pg_catalog.PgCatalog

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.types.YearToSecond


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgTimezoneAbbrevs(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function()
) {
    companion object {

        /**
         * The reference instance of <code>pg_catalog.pg_timezone_abbrevs</code>
         */
        val PG_TIMEZONE_ABBREVS: PgTimezoneAbbrevs = PgTimezoneAbbrevs()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.pg_timezone_abbrevs.abbrev</code>.
     */
    val ABBREV: TableField<Record, String?> = createField(DSL.name("abbrev"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>pg_catalog.pg_timezone_abbrevs.utc_offset</code>.
     */
    val UTC_OFFSET: TableField<Record, YearToSecond?> = createField(DSL.name("utc_offset"), SQLDataType.INTERVAL, this, "")

    /**
     * The column <code>pg_catalog.pg_timezone_abbrevs.is_dst</code>.
     */
    val IS_DST: TableField<Record, Boolean?> = createField(DSL.name("is_dst"), SQLDataType.BOOLEAN, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, arrayOf(
    ))
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.pg_timezone_abbrevs</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.pg_timezone_abbrevs</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.pg_timezone_abbrevs</code> table reference
     */
    constructor(): this(DSL.name("pg_timezone_abbrevs"), null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun `as`(alias: String): PgTimezoneAbbrevs = PgTimezoneAbbrevs(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): PgTimezoneAbbrevs = PgTimezoneAbbrevs(alias, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): PgTimezoneAbbrevs = PgTimezoneAbbrevs(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PgTimezoneAbbrevs = PgTimezoneAbbrevs(name, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(): PgTimezoneAbbrevs = PgTimezoneAbbrevs(DSL.name("pg_timezone_abbrevs"), null, arrayOf()).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
